/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AvlTree;
import AvlTree.AVLTree;

public class App {
    public static void main(String[] args) {
        
        AVLTree tree = new AVLTree();
        
        tree.insert(30);
        tree.insert(40);
        tree.insert(50);
        tree.insert(60);
        tree.insert(55);
       
        System.out.println("===");
        
        tree.show();  
        
    }
}
